git clone https://github.com/AltraMayor/f3
git clone https://github.com/k4m4/kickthemout
git clone https://github.com/maldevel/IPGeoLocation
git clone https://github.com/nimaipatel/brn
git clone https://github.com/nonpop/xkblayout-state
git clone https://github.com/qarmin/czkawka
git clone https://github.com/RUB-NDS/PRET
git clone https://github.com/threat9/routersploit
git clone https://github.com/xmendez/wfuzz
