#!/bin/bash

cd /run/media/user/57020afc-0ec3-49d9-8968-3000c1a37462/dump/pcapng/

echo "copy ..."
while read -r line ; do
        cp "$line" "all/."
done <<< "$(find "dump" -name "*cap*")"
echo "copy done"

echo "hcx-cap ..."
cd all
hcx-cap
echo "hcx-cap done"

echo "rm *.cap *.pcapng ..."
rm -v *.cap *.pcapng
echo "rm done"


