#!/usr/bin/env python3
import sys

if len(sys.argv) < 2:
    print("USAGE: " + sys.argv[0] + " <file.csv> [delim] [clm]")
    print("* delim default = whitepace")
    exit()

items = []

filename = sys.argv[1]
delim = ""
clm = ""
if len(sys.argv) >= 3: delim = sys.argv[2]
if len(sys.argv) >= 4: clm = sys.argv[3]

f = open(filename, 'r')
lines = f.readlines()
f.close()
for i_ in lines:
    i = i_.replace("\n", "")
    if delim: a = i.split(delim)
    else:     a = i.split()
    items.append(a)

if clm:
    for i in items:
        print(i[int(clm)])
else:
    for i in items:
        print(i)


