#!/usr/bin/env python3

import sys

if len(sys.argv) <= 1:
	print("ABOUT: check if string uses utf-8")
	print("USAGE: " + sys.argv[0] + " <file>")
	exit()

file1 = open(sys.argv[1], 'r')
lines1 = file1.readlines()
file1.close()

def checkUTF(s):
	no_special = True
	try:
		s.encode('latin1')
	except UnicodeEncodeError:
		no_special = False
	return no_special

def replaceAP(str):
	str = str.replace("č", "c")
	str = str.replace("Č", "C")
	str = str.replace("ć", "c")
	str = str.replace("Ć", "C")
	str = str.replace("š", "s")
	str = str.replace("Š", "S")
	str = str.replace("ž", "z")
	str = str.replace("Ž", "Z")
	str = str.replace("ð", "dj")
	str = str.replace("đ", "dj")
	str = str.replace("Ð", "Dj")
	return str

for l1 in lines1:
	line1 = l1.replace("\n", "")
	if checkUTF(line1):
		print(line1)
	else:
		print(line1)
		print(replaceAP(line1))

