#!/usr/bin/env python3

# generate wordlist from names

import sys

# print usage
if len(sys.argv) <= 1:
    print("ABOUT: generate wordlist from names")
    print("USAGE: " + sys.argv[0] + " <namesFile>")
    exit()


file_path = sys.argv[1]
file = open(file_path, 'r')
file_lines = file.readlines()
file.close()


print("#!/bin/bash -x")
for i_ in file_lines:
    i = i_.replace("\n", "")
    print(f"hcx-genlst-XXXX '{i}' | strings -n 8 >> new.txt")


print("sort -u new.txt > new_sorted.txt")
