#!/usr/bin/env python3

# generate wordlist from word

import sys
import random
import string


vari = []
while True:
    l = random.choice(string.ascii_lowercase)
    if len(vari) >= 4:
        break

    if l not in vari:
        vari.append(l)

print("".join(vari))

