#!/usr/bin/env python3

#
# USAGE:
# hcx-potfile "/path/for/the/potfile (optional)"   - the script will find the potfile by itself
# hcx-potfile PASS                                 - only print passwords from potfile
# hcx-potfile SORT0                                - sort by clm index (0 = num, 1 = pmk, 2 = essid, 3 = psk)
#

import sys
import os
import subprocess
import codecs
from colorama import Fore, Back, Style
from tabulate import tabulate
from operator import itemgetter

print_pass_only = False
sort_essid = False
sort_index = 0
potfile_path = os.path.expanduser('~') + "/.local/share/hashcat/hashcat.potfile"

for i in sys.argv[1:]:
	if i == "PASS":
		print_pass_only = True
	elif "SORT" in i:
		sort_essid = True
		sort_index = i.split("SORT")[1]
	else:
		potfile_path = i


potfile = open(potfile_path, 'r')
potfile_lines = potfile.readlines()
potfile.close()

if print_pass_only:
	for i in potfile_lines:
		print(i.replace("\n", "").split(":")[1])
else:
	psks = []
	num = 0
	for i in potfile_lines:
		line = i.replace("\n", "")
		if not line: continue
		num += 1
		split_star = line.split("*")
		hash = split_star[0]
		split_colon = split_star[1].split(":")
		essid_hex = split_colon[0]
		psk = split_colon[1]
		essid = str(codecs.decode(essid_hex, "hex"), "utf-8")

		clr_num   = Style.BRIGHT + Fore.YELLOW + str(num) + Style.RESET_ALL
		clr_hash  = Style.BRIGHT + Fore.GREEN  + hash     + Style.RESET_ALL
		clr_essid = Style.BRIGHT + Fore.BLUE   + essid    + Style.RESET_ALL
		clr_psk   = Style.BRIGHT + Fore.RED    + psk      + Style.RESET_ALL
		psks.append([clr_num,clr_hash,clr_essid,clr_psk])

	if sort_essid:
		psks = sorted(psks, key=itemgetter(int(sort_index)))

	print(tabulate(psks, headers=["#", "HASHCAT ID", "ESSID", "PASSWORD"]))
