#!/usr/bin/env python3

# generate wordlist from word

import sys

def genlst(word):
	
	# num variations
	def print_i(word, i):
		print(word + i)
		#print(i + word)
		#print(i + word + i)
	
	# common sufix
	sufix = [
		"!",
		"!!",
		"!!!",
		"012345",
		"0123456",
		"01234567",
		"012345678",
		"0123456789",
		"01234567890",
		"012345678910",
		"12345",
		"123456",
		"1234567",
		"12345678",
		"123456789",
		"1234567890",
		"12345678910",
	]

	for i in sufix:
		print_i(word, i)
	for i in range(0, 10001):
		print_i(word, str(i))
	for x in range(2, 5):
		for y in range(0, 10 ** (x-1)):
			print_i(word, str(y).rjust(x, '0'))


words = []
def addword(word):
	if not word in words:
		words.append(word)

def wordvars(word):
	#addword(word)
	#addword(word.lower())
	#addword(word.upper())
	addword(word.title())
	#addword(word[::-1].lower())
	#addword(word[::-1].upper())
	#addword(word[::-1].title())

	for i in words:
		genlst(i)

if len(sys.argv) <= 1:
	print("ABOUT: generate wordlist from word")
	print("USAGE: " + sys.argv[0] + " <word>")
	exit()

for i in sys.argv[1:]:
	wordvars(i)
