#!/usr/bin/env python3

# generate wordlist from word

import sys

# print usage
if len(sys.argv) <= 1:
	print("ABOUT: generate wordlist from names")
	print("USAGE: " + sys.argv[0] + " <names>")
	exit()



file_path = sys.argv[1]
file = open(file_path, 'r')
file_lines = file.readlines()
file.close()


for i_ in file_lines:
	i = i_.replace("\n", "")
	print(i + i)


for x_ in file_lines:
	x = x_.replace("\n", "")
	for y_ in file_lines:
		y = y_.replace("\n", "")
		if x != y:
			print(x + y)


