#!/usr/bin/env python3

# go through each hash
# put hash in another file
# generate a wordlist for the hash in another file
# generate a bash script which will run hashcat on all the hashes and hash wordlists

import sys
import codecs
from operator import itemgetter

if len(sys.argv) <= 1:
	print("USAGE: " + sys.argv[0] + " <hash(es)File> <auto(optional)>")
	print("if second arg is 'auto', generate automatically")
	exit()

OPTION_AUTO = 0

if len(sys.argv) >= 3:
	if sys.argv[2] == "auto": OPTION_AUTO = 1

hashes_file_path = sys.argv[1]
hashes_file_file = open(hashes_file_path, 'r')
hashes_file_lines = hashes_file_file.readlines()
hashes_file_file.close()

shheader = "#!/bin/sh -x\n"

print(" * leave the hcx-genlst args empty to skip cracking this/current hash")

def hex2str(string):
	try:
		binary_str = codecs.decode(string, "hex")
		return str(binary_str, 'utf-8')
	except Exception as e:
		return "HEX ERROR"


wordlst = []

def wordlst_dupelessAppend(word):
	if not word: return
	if not word in wordlst:
		wordlst.append(word)

def wordlst_append(word):
	wordlst_dupelessAppend(word)
	numlessword = ""
	for c in word:
		if not c.isdigit():
			numlessword += c
	wordlst_dupelessAppend(numlessword)

def wordlst_appendWords(words):
	long = ""
	for word in words:
		 long += word
		 wordlst_append(word)
	wordlst_append(long)
	long = ""
	words.reverse()
	for word in words:
		long += word
	wordlst_append(long)

def wordlst_genessid(essid):
	wordlst_append(essid)
	wordlst_appendWords(essid.split(" "))
	wordlst_appendWords(essid.split("_"))
	wordlst_appendWords(essid.split("-"))

items = []
counter = 0
skipped = 0
for hashes_file_line in hashes_file_lines:
	hashLine = hashes_file_line.replace("\n", "")
	if not hashLine: continue
	counter += 1
	split = hashes_file_line.split("*")
	type = split[1]
	type_str = ""
	if type == "01": type_str = "PMKID"
	if type == "02": type_str = "EAPOL"
	hash  = split[2].upper()
	bssid = split[3].upper()
	mac   = split[4].upper()
	essid = hex2str(split[5])
	print(counter,"\t",type_str,hash,bssid,mac,essid,end=" --> ")

	genlst = ""
	if OPTION_AUTO:
		wordlst = []
		wordlst_genessid(essid)
		for word in wordlst:
			if genlst:
				genlst += " '" + word + "'"
			else:
				genlst += "'" + word + "'"
		print(genlst)
	else:
		try:
			genlst = input(" --> hcx-genlst ")
		except:
			print("")
			quit()
		if not genlst:
			skipped += 1
			print(" -- Skipping... (" + str(skipped) +")")
			continue
	items.append([hashLine,type_str,hash,bssid,mac,essid,genlst,len(wordlst)])

items = sorted(items, key=itemgetter(7))

print("\n+--> gen.sh")

files = []
num = 0
zerostr = len(str(len(items)))

if len(items) != 0:
	with open("gen.sh", 'w') as f_gen:
		f_gen.write(shheader)
		items_l = len(items)
		for i in items:
			num += 1
			num_s = str(num).rjust(zerostr, '0')
			file_1 = "hash" + num_s + ".txt"
			file_2 = "hash" + num_s + ".lst"
		
			with open(file_1, 'w') as f1:
				f1.write(i[0] + "\n")
		
			#comment = f"echo -e \"{i[1]} {i[2]} {i[3]} {i[4]} {i[5]} -> {i[6]}\"\n"
			comment = f"echo '{num}/{items_l}' ; "
			f_gen.write(comment)
			print("|", comment, end="")
			command = "hcx-genlst " + i[6] + " | strings -n 8 > \"" + file_2 + "\" # " + i[5] + "\n"
			f_gen.write(command)
			print("|", command, end="")
			files.append([file_1, file_2, i])


print("\n+--> run.sh")
with open("run.sh", 'w') as f3:
	f3.write(shheader)
	print("|", shheader, end="")
	for i in files:
		line = f"hashcat --quiet -m 22000 {i[0]} -a 0 {i[1]} -w 4 --session \"{i[2][2]}\" 2>/dev/null # {i[2][5]} -> {i[2][6]}\n"
		f3.write(line)
		print("|", line, end="")
	longlists = [
		["names", "/home/user/.vip/lists/wordlists/serbianNames_numbers/nameNUM_mostcommon.txt"],
		["holylst", "/home/user/.vip/lists/wordlists/holylst.txt"],
		["num8", "/home/user/.vip/lists/wordlists/num8.txt"],
	]
	for i in longlists:
		line = f"hashcat -m 22000 {hashes_file_path} -a 0 {i[1]} -w 4 --session \"{i[0]}\" 2>/dev/null\n"
		f3.write(line)
		print("|", line, end="")


print()
print(" -- total:",num)
print(" -- done.")
