#!/usr/bin/env python3

#
# USAGE:
# hc-potfile "/path/for/the/potfile (optional)"   - the script will find the potfile by itself
# hc-potfile PASS                                 - only print passwords from potfile
#


# this script in bash (slow):
'''
INPUT_FILE="$1"
[ -z "$INPUT_FILE" ] && INPUT_FILE="/home/user/.local/share/hashcat/hashcat.potfile"

while read -r line ; do
	#echo "- $line"
	HASH="$(printf "$line" | awk 'BEGIN { FS = "*" } ; { print $1 }')"
	NAME="$(printf "$line" | awk 'BEGIN { FS = "*" } ; { print $2 }' | awk 'BEGIN { FS = ":" } ; { print $1 }' | perl -pe 's/(..)/chr(hex($1))/ge')"
	PASS="$(printf "$line" | awk 'BEGIN { FS = ":" } ; { print $2 }')"
	echo -e "$HASH - $NAME : $PASS"
	#printf "$line" | awk 'BEGIN { FS = "*" } ; { print $6 }' | perl -pe 's/(..)/chr(hex($1))/ge'
done <<< $(cat "$INPUT_FILE")
'''

import sys
import os
import subprocess
import codecs

print_pass_only = False
potfile_path = os.path.expanduser('~') + "/.local/share/hashcat/hashcat.potfile"

for i in sys.argv[1:]:
	if i == "PASS": print_pass_only = True
	else:           potfile_path = i

potfile = open(potfile_path, 'r')
potfile_lines = potfile.readlines()
potfile.close()

if print_pass_only:
	for i in potfile_lines:
		print(i.replace("\n", "").split(":")[1])
else:
	psks = []
	maxlen_num     = 0
	maxlen_hash    = 0
	maxlen_essid   = 0
	maxlen_psk     = 0
	num = 0
	for i in potfile_lines:
		line = i.replace("\n", "")
		if not line: continue
		'''
		hex = line.split("*")[1].split(":")[0]
		print(line.replace(hex, str(codecs.decode(hex, "hex"), "utf-8")))
		'''
		num += 1
		split_star = line.split("*")
		hash = split_star[0]
		split_colon = split_star[1].split(":")
		essid_hex = split_colon[0]
		psk = split_colon[1]
		essid = str(codecs.decode(essid_hex, "hex"), "utf-8")
		l_hash  = len(hash)
		l_essid = len(essid)
		l_psk   = len(psk)
		l_num   = len(str(num))
		if l_hash  > maxlen_hash:  maxlen_hash  = l_hash
		if l_essid > maxlen_essid: maxlen_essid = l_essid
		if l_psk   > maxlen_psk:   maxlen_psk   = l_psk
		if l_num   > maxlen_num:   maxlen_num   = l_num
		psks.append([num, hash, essid, psk])
	for i in psks:
		print(("{:<" + str(maxlen_num) + "} {:<" + str(maxlen_hash) + "} {:<" + str(maxlen_essid) + "} {:<" + str(maxlen_psk) + "}").format(i[0],i[1],i[2],i[3]))
