#!/usr/bin/env python3

import sys
import termios # getch()
import time
import atexit
import RPi.GPIO as GPIO

from scapy.all import *
from threading import Thread
from datetime import datetime
from tabulate import tabulate
from operator import itemgetter

# global stuff
running = True
status = ("STARTED: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S")) # UI status
show_wifis     = True
enable_wifis   = True

# channels to use
channels = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]
ch = 1 # current channel

# wifi (beacon) table
wifis = []
wifi_clms = ["BSSID", "ESSID", "PASSWORD", "PWR", "LAST SEEN", "#", "CH", "CRYPTO", "TIMESTAMP", "PACKETS" ]
wifi_clms_len = len(wifi_clms)
wifi_clm_bssid     = 0
wifi_clm_essid     = 1
wifi_clm_passwd    = 2
wifi_clm_pwr       = 3
wifi_clm_lastseen  = 4
wifi_clm_num       = 5
wifi_clm_ch        = 6
wifi_clm_crypto    = 7
wifi_clm_timestamp = 8
wifi_clm_packets   = 9

sortBy = "#"
sortBy_reverse = False

#
# global things to not touch
#
updateUI_mutex = threading.Lock()
menu_mutex = threading.Lock()
pauseUI_evt = threading.Event()
pauseUI_evt.set()
pauseCHHOP_evt = threading.Event()
pauseCHHOP_evt.set()
g_tc = os.get_terminal_size().columns
g_tl = os.get_terminal_size().lines
# password list from csv file
passwords = [] # BSSID, ESSID, PASSWORD
passwords_count = 0
show_counter = 0
current_wifi = 0

RST_PIN = 25
CS_PIN  = 8
DC_PIN  = 24

RST    = 27
DC     = 25
BL     = 24
bus    = 0
device = 0

# LCD keys
KEY_UP_PIN    = 6
KEY_DOWN_PIN  = 19
KEY_LEFT_PIN  = 5
KEY_RIGHT_PIN = 26
KEY_PRESS_PIN = 13
KEY1_PIN      = 21
KEY2_PIN      = 20
KEY3_PIN      = 16

def checkRoot():
    return os.geteuid() == 0
def term_clear():
    os.system("clear")
def term_cursor_reset():
    print("\033[0;0H", end='')
def term_cursor_hide():
    print("\033[?25l")
def term_cursor_show():
    print("\033[?25h")

def term_getch():
    old_settings = termios.tcgetattr(0)
    new_settings = old_settings[:]
    new_settings[3] &= ~termios.ICANON
    try:
        termios.tcsetattr(0, termios.TCSANOW, new_settings)
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(0, termios.TCSANOW, old_settings)
    return ch
def term_show_print(s):
    global show_counter
    tl = os.get_terminal_size().lines
    if show_counter >= (tl-1): return
    print(s)
    show_counter += 1
def term_show(s):
    global g_tc
    global g_tl
    strings = s.split("\n")
    tc = os.get_terminal_size().columns
    tl = os.get_terminal_size().lines
    if g_tc != tc or g_tl != tl:
        g_tc = tc
        g_tl = tl
        term_clear()
    for i in strings:
        il = len(i)
        if il > tc: term_show_print(i[:tc])
        else:       term_show_print(i + str(" " * int(int(tc)-int(il))))

def loadPasswords(filePath):
    global passwords
    global passwords_count
    f = open(filePath, 'r')
    lines = f.readlines()
    f.close()
    for i_ in lines:
        i = i_.replace("\n", "")
        isplit = i.split("|||")
        if len(isplit) >= 3:
            passwords.append([isplit[0],isplit[1],isplit[2]])
    passwords_count = len(passwords)

# exit handler
@atexit.register
def signal_handler():
    term_cursor_show()

def action_quit():
    global running
    running = False # send signal for the threads to close
    th_ui.join()
    th_hop.join()
    exit()
def action_changeSorting():
    found = False
    isSet = False
    global wifi_clms
    global sortBy
    while True:
        for i in wifi_clms:
            if found:
                sortBy = i
                isSet = True
                break
            if i == sortBy:
                found = True
                continue
        if isSet:
            break
def action_changeSorting_order():
    global sortBy_reverse
    sortBy_reverse = (not sortBy_reverse)
def action_pauseUI():
    global status
    if pauseUI_evt.is_set():
        pauseUI_evt.clear()
        status = "PAUSED"
    else:
        pauseUI_evt.set()
        status = "RESUMED"
def action_pauseCHHOP():
    global status
    if pauseCHHOP_evt.is_set():
        pauseCHHOP_evt.clear()
        status = "PAUSED CHANNEL HOPPER"
    else:
        pauseCHHOP_evt.set()
        status = "RESUMED CHANNEL HOPPER"
def action_show_wifis():
    global show_wifis
    global status
    show_wifis = (not show_wifis)
    if show_wifis: status = "show wifis: on"
    else:          status = "show wifis: off"
def action_clear_wifis():
    global status
    global wifis
    global current_wifi
    wifis = []
    status = "cleared wifi table"
    current_wifi = 0
def action_prevWifi():
    global current_wifi
    global wifis
    current_wifi -= 1
    if current_wifi < -1: current_wifi = -1
def action_nextWifi():
    global current_wifi
    global wifis
    current_wifi += 1
    l = len(wifis)
    if current_wifi > l: current_wifi = l

def channel_get(): return os.popen(f"iw '{interface}' info | grep channel | awk -P '{{print $2}}'").read().replace("\n", "")
def channel_set(i): os.system(f"sudo iw dev '{interface}' set channel {i}")
def action_hopch():
    found = False
    isSet = False
    global channels
    global ch
    while True:
        for i in channels:
            if found:
                ch = i
                channel_set(i)
                isSet = True
                break
            if i == ch:
                found = True
                continue
        if isSet:
            break
def thread_hopch():
    global running
    while running:
        if not pauseCHHOP_evt.is_set(): pauseCHHOP_evt.wait()
        action_hopch()
        time.sleep(1)

def updateUI():

    updateUI_mutex.acquire()

    # get vars
    global ch
    global show_counter
    global current_wifi
    now = datetime.now()
    #timestr = now.strftime("%Y-%m-%d %H:%M:%S.%f")
    timestr = now

    arrowChar = "\u2193"
    if sortBy_reverse: arrowChar = "\u2191"

    term_cursor_reset() # set print pos to 0x0
    show_counter = 0 # reset show counter

    # display stuff
    term_show(f"CH {str(ch).rjust(2)} | {str(timestr).ljust(26)}")
    len_wifis = len(wifis)
    term_show(f"PASS: {passwords_count} | {current_wifi} / {len_wifis-1} ({len_wifis}) | ")
    term_show(f"SORT BY: {arrowChar} {sortBy} | {status}")

    wifis_sorted = sorted(wifis, key=itemgetter(wifi_clms.index(sortBy)), reverse=sortBy_reverse)
    #term_show(str(tabulate(wifis_sorted, headers=wifi_clms, tablefmt="plain")))
    #term_show("\n")

    if len(wifis) > 0:
        try:
            term_show(f"+{'='*45}")
            term_show(f"BSSID.....: {wifis_sorted[current_wifi][wifi_clm_bssid]}")
            term_show(f"ESSID.....: {wifis_sorted[current_wifi][wifi_clm_essid]}")
            term_show(f"PASSWORD..: {wifis_sorted[current_wifi][wifi_clm_passwd]}")
            term_show(f"PWR.......: {wifis_sorted[current_wifi][wifi_clm_pwr]}")
            term_show(f"LAST SEEN.: {wifis_sorted[current_wifi][wifi_clm_lastseen]}")
            term_show(f"#.........: {wifis_sorted[current_wifi][wifi_clm_num]}")
            term_show(f"CH........: {wifis_sorted[current_wifi][wifi_clm_ch]}")
            term_show(f"CRYPTO....: {wifis_sorted[current_wifi][wifi_clm_crypto]}")
            term_show(f"TIMESTAMP.: {wifis_sorted[current_wifi][wifi_clm_timestamp]}")
            term_show(f"PACKETS...: {wifis_sorted[current_wifi][wifi_clm_packets]}")
            term_show(f"+{'='*45}")
        except:
            pass
    updateUI_mutex.release()
def thread_updateUI():
    global running
    while running:
        if not pauseUI_evt.is_set(): pauseUI_evt.wait()
        updateUI()
        time.sleep(0.1)

def callback(packet):
    if packet.haslayer(Dot11Beacon):
        bssid = packet[Dot11].addr2.upper()
        essid = packet[Dot11Elt].info.decode()
        try:    dbm_signal = packet.dBm_AntSignal
        except: dbm_signal = ""
        stats = packet[Dot11Beacon].network_stats()
        channel = stats.get("channel")
        crypto  = stats.get("crypto")
        timestamp = packet[Dot11Beacon].timestamp
        lastseen =  datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        passwd = ""

        # check if wifi exists
        hasWifi = False
        index = 0
        for i in range(0, len(wifis)):
            index = i
            if wifis[i][wifi_clm_bssid] == bssid:
                hasWifi = True
                break

        lst = [None] * wifi_clms_len
        lst[wifi_clm_bssid]     = bssid
        lst[wifi_clm_essid]     = essid
        lst[wifi_clm_pwr]       = dbm_signal
        lst[wifi_clm_lastseen]  = lastseen
        lst[wifi_clm_ch]        = channel
        lst[wifi_clm_crypto]    = crypto
        lst[wifi_clm_timestamp] = timestamp

        if hasWifi:
            lst[wifi_clm_num]     = wifis[index][wifi_clm_num]
            lst[wifi_clm_packets] = wifis[index][wifi_clm_packets]+1
            lst[wifi_clm_passwd]  = wifis[index][wifi_clm_passwd]
            wifis[index] = lst
        else:
            global passwords_count
            if passwords_count:
                global passwords
                for i in passwords:
                    match_bssid = str(bssid).replace(":", "").replace("-", "").lower()
                    match_i     =  str(i[0]).replace(":", "").replace("-", "").lower()
                    if match_bssid == match_i and essid == i[1]:
                        passwd = i[2]
                        break
            lst[wifi_clm_num]     = len(wifis)+1
            lst[wifi_clm_packets] = 1
            lst[wifi_clm_passwd]  = passwd
            wifis.append(lst)

        return # close if

def menu(keyPress):
    menu_mutex.acquire()

    if   keyPress == 1: action_hopch()
    elif keyPress == 2: action_pauseCHHOP()
    elif keyPress == 3: action_prevWifi()
    elif keyPress == 4: action_nextWifi()
    elif keyPress == 5: action_pauseUI()
    elif keyPress == 6: action_quit()
    elif keyPress == 7: action_changeSorting()
    elif keyPress == 8: action_changeSorting_order()
    term_clear()
    updateUI()

    menu_mutex.release()

def menu_callback(channel):
    time.sleep(0.1)
    if GPIO.input(channel) == 1:
        if   channel == KEY_UP_PIN:    menu(1)
        elif channel == KEY_DOWN_PIN:  menu(2)
        elif channel == KEY_LEFT_PIN:  menu(3)
        elif channel == KEY_RIGHT_PIN: menu(4)
        elif channel == KEY_PRESS_PIN: menu(5)
        elif channel == KEY1_PIN:      menu(6)
        elif channel == KEY2_PIN:      menu(7)
        elif channel == KEY3_PIN:      menu(8)

GPIO.setmode(GPIO.BCM)
GPIO.setup(KEY_UP_PIN,    GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(KEY_DOWN_PIN,  GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(KEY_LEFT_PIN,  GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(KEY_RIGHT_PIN, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(KEY_PRESS_PIN, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(KEY1_PIN,      GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(KEY2_PIN,      GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.setup(KEY3_PIN,      GPIO.IN, pull_up_down=GPIO.PUD_UP)

GPIO.add_event_detect(KEY_UP_PIN,    GPIO.BOTH, callback=menu_callback, bouncetime=100)
GPIO.add_event_detect(KEY_DOWN_PIN,  GPIO.BOTH, callback=menu_callback, bouncetime=100)
GPIO.add_event_detect(KEY_LEFT_PIN,  GPIO.BOTH, callback=menu_callback, bouncetime=100)
GPIO.add_event_detect(KEY_RIGHT_PIN, GPIO.BOTH, callback=menu_callback, bouncetime=100)
GPIO.add_event_detect(KEY_PRESS_PIN, GPIO.BOTH, callback=menu_callback, bouncetime=100)
GPIO.add_event_detect(KEY1_PIN,      GPIO.BOTH, callback=menu_callback, bouncetime=100)
GPIO.add_event_detect(KEY2_PIN,      GPIO.BOTH, callback=menu_callback, bouncetime=100)
GPIO.add_event_detect(KEY3_PIN,      GPIO.BOTH, callback=menu_callback, bouncetime=100)

if __name__ == "__main__":

    try:

        argv_len = len(sys.argv)

        if argv_len < 2:
            print("ABOUT: uses scapy to show nearby networks,")
            print("       (optional) and trys to match them with the csv password list")
            print("USAGE: " + sys.argv[0] + " <interface(mon)> <wifipasslst.csv(optional)>")
            print("KEY COMMANDS:")
            print("      q - quit")
            print("      s - change sorting")
            print("      d - change sorting order")
            print("  SPACE - pause")
            print("      c - hop channel")
            print("      C - toggle auto channel hopper")
            print("      w - show wifi table")
            print("      W - clear wifi table")
            print("      j - back")
            print("      k - forward")
            print("")
            exit()

        if not checkRoot():
            print("use root.")
            exit()

        interface = sys.argv[1]
        if argv_len >= 3: loadPasswords(sys.argv[2])

        # clear screen and hide cursor
        term_clear()
        term_cursor_hide()

        # threads (print / channel hopper)
        th_ui  = Thread(target=thread_updateUI)
        th_hop = Thread(target=thread_hopch)

        # start all threads
        th_ui.start()
        th_hop.start()

        # start sniffing
        th_sniff = AsyncSniffer(prn=callback, iface=interface)
        th_sniff.start()

        # handle key input
        while running:
            pressedKey = term_getch()
            if   pressedKey == "q": action_quit()
            elif pressedKey == "s": action_changeSorting()
            elif pressedKey == "d": action_changeSorting_order()
            elif pressedKey == " ": action_pauseUI()
            elif pressedKey == "c": action_hopch()
            elif pressedKey == "C": action_pauseCHHOP()
            elif pressedKey == "w": action_show_wifis()
            elif pressedKey == "W": action_clear_wifis()
            elif pressedKey == "j": action_nextWifi()
            elif pressedKey == "k": action_prevWifi()
            term_clear()
            updateUI()
    except KeyboardInterrupt:
        print("Quitting...")
        running = False
        exit()
