#!/usr/bin/env python3

# print info for hash file

import sys
import os
import subprocess
from colorama import Fore, Back, Style


if len(sys.argv) < 2:
	print("USAGE: " + sys.argv[0] + " <hash(es)File> <search(optional)>")
	exit()

search = ""
if len(sys.argv) >= 3:
	search = sys.argv[2].lower()

hashes_file_path = sys.argv[1]
hashes_file_file = open(hashes_file_path, 'r')
hashes_file_lines = hashes_file_file.readlines()
hashes_file_file.close()

#potfile_file_path = os.path.expanduser('~') + "/.local/share/hashcat/hashcat.potfile"
#potfile_file_file = open(potfile_file_path, 'r')
#potfile_file_lines = potfile_file_file.readlines()
#potfile_file_file.close()

hashcat_items = []
hashcat = subprocess.Popen(['hashcat', '-m', '22000', '--show', hashes_file_path], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
for potfile_file_line in hashcat.stdout.read().decode().split("\n"):
	if not potfile_file_line: continue
	#print(potfile_file_line)
	clms = potfile_file_line.split(":")
	#print(clms)
	hashcat_items.append([clms[0], clms[4]])


items = []
counter = 0
for hashes_file_line in hashes_file_lines:
	hashLine = hashes_file_line.replace("\n", "")
	if not hashLine: continue
	bssid = hashes_file_line.split("*")[3].upper()
	p = subprocess.Popen(['hcxpmktool', '-i', hashLine, '-p', ''], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
	essid = ""
	pmk = ""
	for outL in p.stdout.read().decode().split("\n"):
		if outL.startswith("PMK...............: "):
			pmk = outL.replace("PMK...............: ", "")
			continue
		if outL.startswith("ESSID.............: "):
			essid = outL.replace("ESSID.............: ", "")
			continue
		if pmk != "" and essid != "": break
	if search:
		items.append([hashLine, pmk, bssid, essid])
	else:
		counter += 1
		passwd = ""
		for hcitem in hashcat_items:
			if hcitem[0] in hashLine:
				passwd = hcitem[1]
				break

		clr_counter = Style.BRIGHT + Fore.GREEN   + str(counter).rjust(5, " ") + Style.RESET_ALL
		clr_pmk     = Style.BRIGHT + Fore.RED     + pmk                        + Style.RESET_ALL
		clr_bssid   = Style.BRIGHT + Fore.YELLOW  + bssid                      + Style.RESET_ALL
		clr_essid   = Style.BRIGHT + Fore.BLUE    + essid                      + Style.RESET_ALL
		if passwd:
			clr_passwd = Style.BRIGHT + Fore.GREEN + passwd + Style.RESET_ALL
			print(clr_counter,clr_pmk,clr_bssid,clr_essid,"-->",clr_passwd)
		else:
			print(clr_counter,clr_pmk,clr_bssid,clr_essid)

if search:
	for x in items:
		for y in x:
			if search in y.lower():
				print(x[0])
