#!/bin/bash
echo "-- hcxpcapngtool"
hcxpcapngtool *.pcapng *.cap -E essid.txt -R probeonly.txt -I identity.txt -U username.txt -D deviceinfo.txt -o all.txt >/dev/null 2>/dev/null
echo "-- essid_uniq.txt"
sort -u essid.txt > essid_uniq.txt
echo "-- probeonly_uniq.txt"
sort -u probeonly.txt > probeonly_uniq.txt
echo "-- identity_uniq.txt"
sort -u identity.txt > identity_uniq.txt
echo "-- username_uniq.txt"
sort -u username.txt > username_uniq.txt
echo "-- deviceinfo_uniq.txt"
sort -u deviceinfo.txt > deviceinfo_uniq.txt
echo "-- all_uniq.txt"
sort -u all.txt > all_uniq.txt

echo "-- apuniq.txt"
hcx-uniq all_uniq.txt > apuniq.txt

hcx-rmcracked "apuniq.txt"
