#!/usr/bin/env python3

# print info for hash file

import sys
import os
import subprocess
from colorama import Fore, Back, Style
from operator import itemgetter
from tabulate import tabulate


if len(sys.argv) < 2:
	print("USAGE: " + sys.argv[0] + " <hash(es)File> <search(optional)>")
	exit()

search = ""
if len(sys.argv) >= 3:
	search = sys.argv[2].lower()

hashes_file_path = sys.argv[1]
hashes_file_file = open(hashes_file_path, 'r')
hashes_file_lines = hashes_file_file.readlines()
hashes_file_file.close()

hashcat_items = []
hashcat = subprocess.Popen(['hashcat', '-m', '22000', '--show', hashes_file_path], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
for potfile_file_line in hashcat.stdout.read().decode().split("\n"):
	if not potfile_file_line: continue
	clms = potfile_file_line.split(":")
	hashcat_items.append([clms[0], clms[4]])

items = []
counter = 0
for hashes_file_line in hashes_file_lines:
	hashLine = hashes_file_line.replace("\n", "")
	if not hashLine: continue
	bssid = hashes_file_line.split("*")[3].upper()
	p = subprocess.Popen(['hcxpmktool', '-i', hashLine, '-p', ''], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
	essid = ""
	pmk = ""
	for outL in p.stdout.read().decode().split("\n"):
		if outL.startswith("PMK...............: "):
			pmk = outL.replace("PMK...............: ", "")
			continue
		if outL.startswith("ESSID.............: "):
			essid = outL.replace("ESSID.............: ", "")
			continue
		if pmk != "" and essid != "": break
	passwd = ""
	for hcitem in hashcat_items:
		if hcitem[0] in hashLine:
			passwd = hcitem[1]
			break
	items.append([hashLine, pmk, bssid, essid, passwd])



if search:
	for item in items:
		for clm in item:
			if search in clm.lower():
				print(item[0])
				break
else:
	counter = 0
	data = []
	counter = 0
	for i in sorted(items, key=itemgetter(3)):
		counter += 1
		clr_counter = Style.BRIGHT + Fore.YELLOW  + str(counter) + Style.RESET_ALL
		clr_pmk     = Style.BRIGHT + Fore.GREEN   + i[1]         + Style.RESET_ALL
		clr_bssid   = Style.BRIGHT + Fore.CYAN    + i[2]         + Style.RESET_ALL
		clr_essid   = Style.BRIGHT + Fore.BLUE    + i[3]         + Style.RESET_ALL
		clr_pass    = Style.BRIGHT + Fore.RED     + i[4]         + Style.RESET_ALL
		data.append([clr_counter,clr_pmk,clr_bssid,clr_essid,clr_pass])
	print(tabulate(data, headers=["#", "PMK", "BSSID", "ESSID", "PASSWORD"]))


