#!/usr/bin/env python3

import sys
import codecs
import subprocess

if len(sys.argv) < 2:
    print("ABOUT: generate password.csv for hcx-wifi")
    print("USAGE: " + sys.argv[0] + " <hash(es)File> > wifipasslst.csv")
    exit()

def hex2str(string):
    try:
        binary_str = codecs.decode(string, "hex")
        return str(binary_str, 'utf-8')
    except Exception as e:
        return "HEX ERROR"

hashes_file_path = sys.argv[1]
hashes_file_file = open(hashes_file_path, 'r')
hashes_file_lines = hashes_file_file.readlines()
hashes_file_file.close()

hashcat_items = []
hashcat = subprocess.Popen(['hashcat', '-m', '22000', '--show', hashes_file_path], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
for potfile_file_line in hashcat.stdout.read().decode().split("\n"):
    if not potfile_file_line: continue
    clms = potfile_file_line.split(":")
    hashcat_items.append([clms[0], clms[4]])

items = []
counter = 0
for hashes_file_line in hashes_file_lines:
    hashLine = hashes_file_line.replace("\n", "")
    if not hashLine: continue
    split = hashes_file_line.split("*")
    bssid = split[3].upper()
    mac   = split[4].upper()
    essid = hex2str(split[5])

    passwd = ""
    for hcitem in hashcat_items:
        if hcitem[0] in hashLine:
            passwd = hcitem[1]
            break

    print(f"{bssid}|||{essid}|||{passwd}")
