#!/usr/bin/env python3

# generate wordlist from word

import sys

# num variations
def print_wi(word,  i): print(word + i)
def print_iw(word,  i): print(i + word)
def print_iwi(word, i): print(i + word + i)

def genlst(word, callback):
	# common sufix
	sufix = [
		"!",
		"!!",
		"!!!",
		".",
		"..",
		"...",
		"@"
		"@@",
		"@@@",
		"#",
		"12345",
		"123456",
		"1234567",
		"12345678",
		"123456789",
		"1234567890",
		"12345678910",
		"012345",
		"0123456",
		"01234567",
		"012345678",
		"0123456789",
		"01234567890",
		"012345678910",
	]

	for i in sufix:
		callback(word, i)
	for i in range(0, 10001):
		callback(word, str(i))
	for x in range(2, 6):
		for y in range(0, 10 ** (x-1)):
			callback(word, str(y).rjust(x, '0'))

words = []
def addword(word):
	# don't add dupes to list
	if not word in words:
		words.append(word)

# add word variations to list
def wordvari(word):
	addword(word)
	addword(word.lower())
	addword(word.upper())
	addword(word.title())
	#addword(word[::-1].lower())
	#addword(word[::-1].upper())
	#addword(word[::-1].title())

# print usage
if len(sys.argv) <= 1:
	print("ABOUT: generate wordlist from word")
	print("USAGE: " + sys.argv[0] + " <word>")
	exit()

# get all word variations from cmd args
for i in sys.argv[1:]:
	wordvari(i)

# just print word variations
for i in words:
	print(i)

# word + nums
for i in words:
	genlst(i, print_wi)
	genlst(i, print_iw)
	genlst(i, print_iwi)


