#!/usr/bin/env python3

# go through each hash
# put hash in another file
# generate a wordlist for the hash in another file
# generate a bash script which will run hashcat on all the hashes and hash wordlists

import sys
import codecs

if len(sys.argv) < 2:
	print("USAGE: " + sys.argv[0] + " <hash(es)File>")
	exit()

hashes_file_path = sys.argv[1]
hashes_file_file = open(hashes_file_path, 'r')
hashes_file_lines = hashes_file_file.readlines()
hashes_file_file.close()

shheader = "#!/bin/bash\n"

print(" * leave the hcx-genlst args empty to skip cracking this/current hash")

def hex2str(string):
	try:
		binary_str = codecs.decode(string, "hex")
		return str(binary_str, 'utf-8')
	except Exception as e:
		return "HEX ERROR"

items = []
counter = 0
skipped = 0
for hashes_file_line in hashes_file_lines:
	hashLine = hashes_file_line.replace("\n", "")
	if not hashLine: continue
	counter += 1
	split = hashes_file_line.split("*")
	type = split[1]
	type_str = ""
	if type == "01": type_str = "PMKID"
	if type == "02": type_str = "EAPOL"
	hash  = split[2].upper()
	bssid = split[3].upper()
	mac   = split[4].upper()
	essid = hex2str(split[5])
	print(counter,"\t",type_str,hash,bssid,mac,essid,end="")

	genlst = ""
	try:
		genlst = input(" --> hcx-genlst ")
	except:
		print("")
		quit()
	if not genlst:
		skipped += 1
		print(" -- Skipping... (" + str(skipped) +")")
		continue
	items.append([hashLine,type_str,hash,bssid,mac,essid,genlst])

print("\n+--> gen.sh")

files = []
num = 0
zerostr = len(str(len(items)))

if len(items) != 0:
	with open("gen.sh", 'w') as f_gen:
		f_gen.write(shheader)
		for i in items:
			num += 1
			num_s = str(num).rjust(zerostr, '0')
			file_1 = "hash" + num_s + ".txt"
			file_2 = "hash" + num_s + ".lst"
		
			with open(file_1, 'w') as f1:
				f1.write(i[0] + "\n")
		
			comment = f"echo -e \"{i[1]} {i[2]} {i[3]} {i[4]} {i[5]} -> {i[6]}\"\n"
			f_gen.write(comment)
			print("|", comment, end="")
			command = "hcx-genlst " + i[6] + " | strings -n 8 > \"" + file_2 + "\"\n"
			f_gen.write(command)
			print("|", command, end="")
			files.append([file_1, file_2, i])


print("\n+--> run.sh")
with open("run.sh", 'w') as f3:
	f3.write(shheader)
	print("|", shheader, end="")
	for i in files:
		line = f"hashcat -m 22000 {i[0]} -a 0 {i[1]} -w 4 --session \"{i[2][2]}\" # {i[2][1]} {i[2][2]} {i[2][3]} {i[2][4]} {i[2][5]} -> {i[2][6]}\n"
		f3.write(line)
		print("|", line, end="")
	longlists = [
		["rockyou", "/home/user/.vip/lists/wordlists/rockyou_english_serbian_min8.txt"],
		["names", "/home/user/.vip/lists/wordlists/serbianNames_numbers/nameNUM_NAMENUM_NameNUM.txt"],
		["num8", "/home/user/.vip/lists/wordlists/num8.txt"],
	]
	for i in longlists:
		line = f"hashcat -m 22000 {hashes_file_path} -a 0 {i[1]} -w 4 --session \"{i[0]}\"\n"
		f3.write(line)
		print("|", line, end="")


print()
print(" -- total:",num)
print(" -- done.")
