#!/bin/bash

echo "-- passlst.csv"
hcx-wifi-genpasslst "$1" | sort -u > passlst.csv

echo "-- hashcat_cracked.txt"
hashcat -m 22000 --show "$1" > hashcat_cracked.txt

echo "-- hashcat_cracked_idonly.txt"
echo -ne "" > hashcat_cracked_idonly.txt
while read -r line ; do
    ID=$(echo "$line" | awk -F ":" '{printf $1}')
    echo "$ID" >> hashcat_cracked_idonly.txt
done <<< "$(cat hashcat_cracked.txt)"

echo "-- cracked.txt"
lines-inline "$1" hashcat_cracked_idonly.txt > cracked.txt
echo "-- uncracked.txt"
hcx-rmhashes "$1" cracked.txt > uncracked.txt

