#!/usr/bin/env python3

# generate wordlist from names

import sys

# print usage
if len(sys.argv) <= 1:
    print("ABOUT: generate wordlist from names")
    print("USAGE: " + sys.argv[0] + " <namesFile>")
    exit()


middle = ""
if len(sys.argv) >= 3:
    middle = sys.argv[2]

file_path = sys.argv[1]
file = open(file_path, 'r')
file_lines = file.readlines()
file.close()


for i_ in file_lines:
    i = i_.replace("\n", "")
    print(i + middle + i)

