#!/usr/bin/env python3

import sys
import codecs

if len(sys.argv) < 2:
    print("USAGE: " + sys.argv[0] + " <hash(es)File>")
    exit()

def hex2str(string):
    try:
        binary_str = codecs.decode(string, "hex")
        return str(binary_str, 'utf-8')
    except Exception as e:
        return "HEX ERROR"

hashes_file_path = sys.argv[1]
hashes_file_file = open(hashes_file_path, 'r')
hashes_file_lines = hashes_file_file.readlines()
hashes_file_file.close()

def rslatin_check(s):
    if "č" in s: return True
    if "Č" in s: return True
    if "ć" in s: return True
    if "Ć" in s: return True
    if "š" in s: return True
    if "Š" in s: return True
    if "ž" in s: return True
    if "Ž" in s: return True
    if "ð" in s: return True
    if "đ" in s: return True
    if "Ð" in s: return True
    return False

def rslatin_replace(s):
    s = s.replace("č", "c")
    s = s.replace("Č", "C")
    s = s.replace("ć", "c")
    s = s.replace("Ć", "C")
    s = s.replace("š", "s")
    s = s.replace("Š", "S")
    s = s.replace("ž", "z")
    s = s.replace("Ž", "Z")
    s = s.replace("ð", "dj")
    s = s.replace("đ", "dj")
    s = s.replace("Ð", "Dj")
    return s

counter = 0
for hashes_file_line in hashes_file_lines:
    hashLine = hashes_file_line.replace("\n", "")
    if not hashLine: continue
    essid = hex2str(hashes_file_line.split("*")[5])
    if rslatin_check(essid):
        print(hashLine)

