#!/usr/bin/env python3

import sys
import termios # getch()
import time
import atexit

from scapy.all import *
from threading import Thread
from datetime import datetime
from tabulate import tabulate
from operator import itemgetter
from colorama import Fore, Back, Style

# global stuff
running = True

ch = 1
status = ("STARTED: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S")) # UI status

# enable/show table vars
show_wifi = True
show_probes = False
enable_probes = False

# password list from csv file
passwords = [] # BSSID, ESSID, PASSWORD
passwords_count = 0

OPTION_VENDOR = 1

# global things to not touch
updateUI_mutex = threading.Lock()
pauseUI_evt = threading.Event()
pauseUI_evt.set()
g_tc = os.get_terminal_size().columns
g_tl = os.get_terminal_size().lines

# wifi (beacon) table
wifis = []
wifi_clms = ["BSSID", "ESSID", "PASSWORD", "PWR", "LAST SEEN", "#", "CH", "CRYPTO", "TIMESTAMP", "PACKETS" ]
wifi_clms_len = len(wifi_clms)
wifi_clm_bssid     = 0
wifi_clm_essid     = 1
wifi_clm_passwd    = 2
wifi_clm_pwr       = 3
wifi_clm_lastseen  = 4
wifi_clm_num       = 5
wifi_clm_ch        = 6
wifi_clm_crypto    = 7
wifi_clm_timestamp = 8
wifi_clm_packets   = 9

sortBy = "#"
sortBy_reverse = False

# probe table
probes = []
probe_clms = [ "TYPE", "STATION", "BSSID", "ESSID", "CH", "PWR", "LAST SEEN", "MAC TIMESTAMP", "PACKETS", "VENDOR" ]
probe_clms_len = len(probe_clms)
probe_clm_type      = 0
probe_clm_station   = 1
probe_clm_bssid     = 2
probe_clm_essid     = 3
probe_clm_ch        = 4
probe_clm_pwr       = 5
probe_clm_lastseen  = 6
probe_clm_timestamp = 7
probe_clm_packets   = 8
probe_clm_vendor    = 9

def clearScreen():
	os.system("clear")

# print string but make sure it fits according to terminal size
def show(s):
	strings = s.split("\n")
	tc = os.get_terminal_size().columns
	tl = os.get_terminal_size().lines
	global g_tc
	global g_tl
	if g_tc != tc or g_tl != tl:
		g_tc = tc
		g_tl = tl
		clearScreen()
	for i in strings:
		il = len(i)
		if il > tc: print(i[:tc])
		else:       print(i + str(" " * int(int(tc)-int(il))))


if OPTION_VENDOR:
	ouifile_path = "/home/user/.vip/scripts/mac2ven.lst"
	ouifile = open(ouifile_path, 'r')
	ouifile_lines = ouifile.readlines()
	ouifile.close()

	mac2ven_cache = [] # this makes if way faster
	def mac2ven(mac):
		mac2check = mac.replace(":", "").replace("-", "").upper()[0:6]
		for i in mac2ven_cache:
			if mac2check == i[0]: return i[1]
		for y_ in ouifile_lines:
			y = y_.replace("\n", "")
			split = y.split("\t")
			split_l = len(split)
			oui_mac = ""
			oui_ven = ""
			if split_l >= 1: oui_mac = split[0]
			if split_l >= 2: oui_ven = split[1]
			if mac2check == oui_mac:
				mac2ven_cache.append([oui_mac, oui_ven])
				return oui_ven
		return ""
else:
	def mac2ven(mac):
		return ""

# sniff callback
# this is what updates the wifi list
def callback(packet):
	if packet.haslayer(Dot11Beacon):
		bssid = packet[Dot11].addr2.upper()
		essid = packet[Dot11Elt].info.decode()
		try:    dbm_signal = packet.dBm_AntSignal
		except: dbm_signal = ""
		stats = packet[Dot11Beacon].network_stats()
		channel = stats.get("channel")
		crypto  = stats.get("crypto")
		timestamp = packet[Dot11Beacon].timestamp
		lastseen =  datetime.now().strftime("%Y-%m-%d %H:%M:%S")
		passwd = ""

		# check if wifi exists
		hasWifi = False
		index = 0
		for i in range(0, len(wifis)):
			index = i
			if wifis[i][wifi_clm_bssid] == bssid:
				hasWifi = True
				break

		lst = [None] * wifi_clms_len
		lst[wifi_clm_bssid]     = bssid
		lst[wifi_clm_essid]     = essid
		lst[wifi_clm_pwr]       = dbm_signal
		lst[wifi_clm_lastseen]  = lastseen
		lst[wifi_clm_ch]        = channel
		lst[wifi_clm_crypto]    = crypto
		lst[wifi_clm_timestamp] = timestamp
		
		if hasWifi:
			lst[wifi_clm_num]     = wifis[index][wifi_clm_num]
			lst[wifi_clm_packets] = wifis[index][wifi_clm_packets]+1
			lst[wifi_clm_passwd]  = wifis[index][wifi_clm_passwd]
			wifis[index] = lst
		else:
			global passwords_count
			if passwords_count:
				global passwords
				for i in passwords:
					match_bssid = str(bssid).replace(":", "").replace("-", "").lower()
					match_i     =  str(i[0]).replace(":", "").replace("-", "").lower()
					if match_bssid == match_i and essid == i[1]:
						passwd = i[2]
						break
			lst[wifi_clm_num]     = len(wifis)+1
			lst[wifi_clm_packets] = 1
			lst[wifi_clm_passwd]  = passwd
			wifis.append(lst)
		
		return # close if

	if enable_probes:
		ptype = ""
		has_Dot11ProbeReq  = packet.haslayer(Dot11ProbeReq)
		has_Dot11ProbeResp = packet.haslayer(Dot11ProbeResp)

		if has_Dot11ProbeReq or has_Dot11ProbeResp:
			ptype = ""
			bssid = ""
			station = ""

			if has_Dot11ProbeReq:
				ptype = "ProbeReq"
				bssid = packet[Dot11].addr1.upper()
				station = packet[Dot11].addr2.upper()
			if has_Dot11ProbeResp:
				ptype = "ProbeResp"
				bssid = packet[Dot11].addr2.upper()
				station = packet[Dot11].addr1.upper()

			try:    essid = packet[Dot11Elt].info.decode()
			except: essid = ""
			try:    channel = packet.channel
			except: channel = ""
			try:    dbm_signal = packet.dBm_AntSignal
			except: dbm_signal = ""
			lastseen =  datetime.now().strftime("%Y-%m-%d %H:%M:%S")
			try:    timestamp = packet.mac_timestamp
			except: timestamp = ""

			# check if probe exists
			hasProbe = False
			index = 0
			for i in range(0, len(probes)):
				index = i
				if probes[i][probe_clm_station] == station and probes[i][probe_clm_type] == ptype:
					hasProbe = True
					break

			lst = [None] * probe_clms_len
			lst[probe_clm_type]      = ptype
			lst[probe_clm_station]   = station
			lst[probe_clm_essid]     = essid
			lst[probe_clm_ch]        = channel
			lst[probe_clm_pwr]       = dbm_signal
			lst[probe_clm_lastseen]  = lastseen
			lst[probe_clm_timestamp] = timestamp

			if hasProbe:
				lst[probe_clm_bssid] = probes[index][probe_clm_bssid]
				if not bssid in lst[probe_clm_bssid]: lst[probe_clm_bssid].append(bssid)
				lst[probe_clm_packets] = probes[index][probe_clm_packets]+1
				lst[probe_clm_vendor]  = probes[index][probe_clm_vendor]
				probes[index] = lst
			else:
				lst[probe_clm_bssid] = []
				lst[probe_clm_bssid].append(bssid)
				lst[probe_clm_vendor]  = mac2ven(station)
				lst[probe_clm_packets] = 1
				probes.append(lst)

	# has_Dot11Deauth    = packet.haslayer(Dot11Deauth)




def updateUI():

	updateUI_mutex.acquire()

	# get vars
	global ch
	now = datetime.now()
	#timestr = now.strftime("%Y-%m-%d %H:%M:%S.%f")
	timestr = now

	arrowChar = "\u2193"
	if sortBy_reverse: arrowChar = "\u2191"

	# set print pos to 0x0
	print("\033[0;0H", end='')

	# display stuff
	show(f"CH {str(ch).rjust(2)} | {str(timestr).ljust(26)} | PASS: {passwords_count} | {status}")
	show(f"COUNT: {len(wifis)}")
	show(f"SORT BY: {arrowChar} {sortBy}")

	if show_wifi:
		wifis_sorted = sorted(wifis, key=itemgetter(wifi_clms.index(sortBy)), reverse=sortBy_reverse)
		show(str(tabulate(wifis_sorted, headers=wifi_clms)))
		show("\n")
	
	if show_probes:
		probes_static = []
		probes_dupe = []
		for i in probes:
			x = i.copy()
			probes_static.append(x)
			probes_dupe.append(x)

		for index in range(len(probes_static)): # for each probe
			nums = []
			for y in probes_static[index][probe_clm_bssid]: # for each probe's bssids
				found = False
				found_num = ""
				for i in wifis: # find bssid in wifi list
					if y == "FF:FF:FF:FF:FF:FF":
						found = True
						found_num = "*"
						break
					if y == i[wifi_clm_bssid]: # if wifi bssid = probe bssid
						found = True
						found_num = str(i[wifi_clm_num])
						break
				if found and (not found_num in nums): nums.append(found_num)
				else: nums.append(y)

			probes_dupe[index][probe_clm_bssid] = str(nums).replace(" ", "").replace("[", "").replace("]", "").replace("'", "")

		#show(str(tabulate(probes, headers=probe_clms)))
		show(str(tabulate(probes_dupe, headers=probe_clms)))
		show("\n")

	updateUI_mutex.release()


def thread_updateUI():
	global running
	while running:
		if not pauseUI_evt.is_set():
			pauseUI_evt.wait()
		updateUI()
		time.sleep(0.1)

#channels = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ]
channels = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ]

def hopch(i):
	os.system(f"sudo iw dev '{interface}' set channel {i}")

def thread_hopch():
	global ch
	global running
	while running:
		for i in channels:
			ch = i
			hopch(i)
			time.sleep(1)

def getch():
	old_settings = termios.tcgetattr(0)
	new_settings = old_settings[:]
	new_settings[3] &= ~termios.ICANON
	try:
		termios.tcsetattr(0, termios.TCSANOW, new_settings)
		ch = sys.stdin.read(1)
	finally:
		termios.tcsetattr(0, termios.TCSANOW, old_settings)
	return ch

def changeSorting():
	found = False
	isSet = False
	global wifi_clms
	global sortBy
	while True:
		for i in wifi_clms:
			if found:
				sortBy = i
				isSet = True
				break
			if i == sortBy:
				found = True
				continue
		if isSet:
			break


# exit handler
@atexit.register
def signal_handler():
	# show cursor
	print("\033[?25h")

def is_root():
    return os.geteuid() == 0

if __name__ == "__main__":

	try:

		argv_len = len(sys.argv)

		if argv_len < 2:
			print("ABOUT: uses scapy to show nearby networks,")
			print("       (optional) and trys to match them with the csv password list")
			print("USAGE: " + sys.argv[0] + " <interface(mon)> <wifipasslst.csv(optional)>")
			print("KEY COMMANDS:")
			print("  q     - quit")
			print("  s     - change sorting column")
			print("  a     - change sorting order")
			print("  x     - clear wifi (beacon) table")
			print("  X     - show/hide wifi (beacon) table")
			print("  z     - clear probe table")
			print("  Z     - show/hide probe table")
			print("  p     - toggle probe info collection")
			print("  SPACE - pause")
			exit()

		if not is_root():
			print("use root.")
			exit()

		interface = sys.argv[1]

		if argv_len >= 3:
			file_pass_path = sys.argv[2]
			file_pass = open(file_pass_path, 'r')
			file_pass_lines = file_pass.readlines()
			file_pass.close()
			for i_ in file_pass_lines:
				i = i_.replace("\n", "")
				isplit = i.split("|||")
				if len(isplit) >= 3:
					passwords.append([isplit[0],isplit[1],isplit[2]])
			passwords_count = len(passwords)

		# clear screen and hide cursor
		clearScreen()
		print("\033[?25l")

		# threads (print / channel hopper)
		th_ui  = Thread(target=thread_updateUI)
		th_hop = Thread(target=thread_hopch)
	
		# start all threads
		th_ui.start()
		th_hop.start()

		# start sniffing
		th_sniff = AsyncSniffer(prn=callback, iface=interface)
		th_sniff.start()

		# handle key input
		while running:
			pressedKey = getch()

			if pressedKey == "q":
				running = False # send signal for the threads to close
				th_ui.join()
				th_hop.join()
				exit()
			elif pressedKey == "s":
				changeSorting()
			elif pressedKey == "a":
				clearScreen()
				sortBy_reverse = (not sortBy_reverse)
			elif pressedKey == "x":
				wifis = []
				status = "cleared wifi table"
			elif pressedKey == "X":
				show_wifi = (not show_wifi)
				if show_wifi: status = "show wifi: on"
				else:         status = "show wifi: off"
			elif pressedKey == "z":
				probes = []
				status = "cleared probe table"
			elif pressedKey == "Z":
				show_probes = (not show_probes)
				if show_probes: status = "show probes: on"
				else:           status = "show probes: off"
			elif pressedKey == "p":
				enable_probes = (not enable_probes)
				if enable_probes: status = "probe collection: on"
				else:             status = "probe collection: off"
			elif pressedKey == " ":
				if pauseUI_evt.is_set():
					pauseUI_evt.clear()
					status = "RESUMED"
				else:
					pauseUI_evt.set()
					status = "PAUSED"

			clearScreen()
			updateUI()
	except KeyboardInterrupt:
		print("Quitting...")
		running = False
		quit()
