#!/usr/bin/env python3

# print info for hash file

import sys
import os
import subprocess

if len(sys.argv) < 2:
	print("USAGE: " + sys.argv[0] + " <hash(es)File> <search(optional)>")
	exit()

search = ""
if len(sys.argv) >= 3:
	search = sys.argv[2].lower()

hashes_file_file = open(sys.argv[1], 'r')
hashes_file_lines = hashes_file_file.readlines()
hashes_file_file.close()

items = []
counter = 0
for hashes_file_line in hashes_file_lines:
	hashLine = hashes_file_line.replace("\n", "")
	if not hashLine: continue
	bssid = hashes_file_line.split("*")[3].upper()
	p = subprocess.Popen(['hcxpmktool', '-i', hashLine, '-p', ''], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
	essid = ""
	pmk = ""
	for outL in p.stdout.read().decode().split("\n"):
		if outL.startswith("PMK...............: "):
			pmk = outL.replace("PMK...............: ", "")
			continue
		if outL.startswith("ESSID.............: "):
			essid = outL.replace("ESSID.............: ", "")
			continue
		if pmk != "" and essid != "": break
	if search:
		items.append([hashLine, pmk, bssid, essid])
	else:
		counter += 1
		print(str(counter).rjust(5, " "),pmk,bssid,essid)

if search:
	for x in items:
		for y in x:
			if search in y.lower():
				print(x[0])
