#!/usr/bin/env python3
import codecs
import sys

if len(sys.argv) == 1:
	print("USAGE: " + sys.argv[0] + " hex")
	exit()

try:
	string = sys.argv[1]
	binary_str = codecs.decode(string, "hex")
	print(str(binary_str, 'utf-8'))
except Exception as e:
	print(e)
