#!/usr/bin/env python3

# go throguh each line of file
# and find matching substring lines from antoher file
# print out matching lines

import sys

if len(sys.argv) <= 2:
	print("USAGE: " + sys.argv[0] + " <file1> <file2>")
	exit()

file1 = open(sys.argv[1], 'r')
lines1 = file1.readlines()
file1.close()

file2 = open(sys.argv[2], 'r')
lines2 = file2.readlines()
file2.close()


for l1 in lines1:
	line1 = l1.replace("\n", "")
	exists = False
	for l2 in lines2:
		line2 = l2.replace("\n", "")
		if line2 in line1:
			print(line1)
			break

