#!/usr/bin/env python3
import sys
import json

if len(sys.argv) == 1:
    print("USAGE: " + sys.argv[0] + " file.json")
    exit()

f = open(sys.argv[1],)
data = json.load(f)
f.close()

print("# CommandQue")
for i in data['CommandQue']:
    print(i)


