#!/usr/bin/env python3
import sys
import json
from datetime import datetime

if len(sys.argv) == 1:
    print("USAGE: " + sys.argv[0] + " file.json")
    exit()

f = open(sys.argv[1],)
data = json.load(f)
f.close()

def convDate(d):
    date = datetime.strptime(d, '%Y-%m-%dT%H:%M:%S.%fZ')
    date_s = str(date)
    if len(date_s) == 19: date_s = date_s + "       "
    return date_s

print("# time | latitude | longitude | altitude | accuracy | speed")
print("+----------------------------------------------------------")
for i in data['GPSData']:
    t = convDate(i['time'])
    la = i['latitude']
    lo = i['longitude']
    al = i['altitude']
    ac = i['accuracy']
    sp = i['speed']

    print(t,'|',la,"|",lo,"|",al,"|",ac,"|",sp)
