#!/usr/bin/env python3
import sys
import json
import datetime

if len(sys.argv) == 1:
    print("USAGE: " + sys.argv[0] + " file.json")
    exit()

# open file read data
f = open(sys.argv[1],)
data = json.load(f)
f.close()

# get contacts
contacts = []
for i in data['contacts']:
    contacts.append(i)

def convDate(utc_date):
    date = datetime.datetime.fromtimestamp(int(utc_date) / 1e3)
    date_s = str(date)
    if len(date_s) == 19: date_s = date_s + "       "
    return date_s

def convNumber(n):
    ret = n
    for i in contacts:
        number = n
        conNumb = i['phoneNo']

        conNumb_ = conNumb
        if   conNumb_[0] == "0": conNumb_ = conNumb_[1:]
        elif conNumb_[0] == "+": conNumb_ = conNumb_[4:]

        number_ = number
        if   number_[0] == "0": number_ = number_[1:]
        elif number_[0] == "+": number_ = number_[4:]

        if conNumb_ == number_:
            ret = n + " (" + i['name'] + ")"
            break
    return ret

def convType(t):
    tt = int(t)
    if tt == 1: return "IN"
    if tt == 2: return "OUT"
    if tt == 3: return "MISS"
    return "UNKNOWN"


# sort by date
# newest go down
data_sorted = sorted(data['CallData'], key=lambda x : x['date'], reverse=False)

for i in data_sorted:
    date = ""
    try:    date = convDate(i['date'])
    except: date = "NULL"

    phoneNo = ""
    try:    phoneNo = convNumber(i['phoneNo'])
    except: phoneNo = "NULL"

    name = ""
    try:    name = i['name']
    except: name = "NULL"

    duration = ""
    try:    duration = i['duration']
    except: duration = "NULL"

    type_ = ""
    try:    type_ = convType(i['type'])
    except: type_ = "NULL"

    print(date,"|",phoneNo,"|",name,"|",duration,"|",type_)
