#!/usr/bin/env python3
import sys
import json
from datetime import datetime

if len(sys.argv) == 1:
    print("USAGE: " + sys.argv[0] + " file.json")
    exit()

f = open(sys.argv[1],)
data = json.load(f)
f.close()

def convDate(utc_date):
    ret = ""
    try:
        date = datetime.fromtimestamp(int(utc_date) / 1e3)
        date_s = str(date)
        if len(date_s) == 19: date_s = date_s + "       "
        ret = date_s
    except:
        pass
    return ret

for i in data['notificationLog']:
    print(i)

for i in data['notificationLog']:
    a = ""
    t = ""
    p = ""
    c = ""
    try:
        p = i['postTime']
        a = i['appName']
        t = i['title'].replace("\n", "")
        c = i['content']
    except:
        pass

    print(convDate(p),"|",a,"|",t,"|",c)
