#!/usr/bin/env python3
import sys
import json
import datetime
from colorama import Fore, Back, Style

# check args
if len(sys.argv) == 1:
    print("USAGE: " + sys.argv[0] + " file.json")
    exit()

# open file read data
f = open(sys.argv[1],)
data = json.load(f)
f.close()

# get contacts
contacts = []
for i in data['contacts']:
    contacts.append(i)

def convDate(utc_date):
    date = datetime.datetime.fromtimestamp(int(utc_date) / 1e3)
    date_s = str(date)
    if len(date_s) == 19: date_s = date_s + "       "
    return Fore.YELLOW + Style.NORMAL + date_s + Style.RESET_ALL

def convMsg(t, b):
    body = b.replace("\n", "")
    g = ""
    if int(t) == 1: g = Fore.GREEN + Style.NORMAL + "\u2193" + " " + body + Style.RESET_ALL
    else:           g = Fore.BLUE  + Style.NORMAL + "\u2191" + " " + body + Style.RESET_ALL
    return g

def convRead(r):
    rr = int(r)
    if rr == 1: return Fore.BLUE + Style.NORMAL + u'\N{check mark}' + Style.RESET_ALL
    return " "

def convNumber(n):
    ret = n
    for i in contacts:
        number = n
        conNumb = i['phoneNo']

        conNumb_ = conNumb
        if   conNumb_[0] == "0": conNumb_ = conNumb_[1:]
        elif conNumb_[0] == "+": conNumb_ = conNumb_[4:]

        number_ = number
        if   number_[0] == "0": number_ = number_[1:]
        elif number_[0] == "+": number_ = number_[4:]

        if conNumb_ == number_:
            ret = n + " (" + i['name'] + ")"
            break
    return Fore.CYAN + Style.NORMAL + ret + Style.RESET_ALL

# sort by date
# newest go down
data_sorted = sorted(data['SMSData'], key=lambda x : x['date'], reverse=False)

print("# sms")

for i in data_sorted:
    pd = convDate(i['date'])
    pa = convNumber(i['address'])
    pr = convRead(i['read'])
    msg = convMsg(i['type'], i['body'])
    print("{} | {} | {} {}".format(pd, pa, pr, msg))

