#!/usr/bin/env python3

import sys

if len(sys.argv) <= 1:
	print("ABOUT: if string contains [čćšžðđ] then add a string without those chars")
	print("USAGE: " + sys.argv[0] + " <fileWithStrings>")
	exit()

file1 = open(sys.argv[1], 'r')
lines1 = file1.readlines()
file1.close()

def rslatin_check(s):
	if "č" in s: return True
	if "Č" in s: return True
	if "ć" in s: return True
	if "Ć" in s: return True
	if "š" in s: return True
	if "Š" in s: return True
	if "ž" in s: return True
	if "Ž" in s: return True
	if "ð" in s: return True
	if "đ" in s: return True
	if "Ð" in s: return True
	return False

def rslatin_replace(s):
	s = s.replace("č", "c")
	s = s.replace("Č", "C")
	s = s.replace("ć", "c")
	s = s.replace("Ć", "C")
	s = s.replace("š", "s")
	s = s.replace("Š", "S")
	s = s.replace("ž", "z")
	s = s.replace("Ž", "Z")
	s = s.replace("ð", "dj")
	s = s.replace("đ", "dj")
	s = s.replace("Ð", "Dj")
	return s

for l1 in lines1:
	line1 = l1.replace("\n", "")
	if rslatin_check(line1):
		print(rslatin_replace(line1))
	else:
		print(line1)

