#!/usr/bin/env python3

import sys
from operator import itemgetter


if len(sys.argv) < 2:
    print("ABOUT: count string len")
    print("USAGE: " + sys.argv[0] + " <file>")
    exit()

file_path = sys.argv[1]
file_file = open(file_path, 'r')
file_lines = file_file.readlines()
file_file.close()

items = []
counter = 0
lines_l = len(file_lines)
for i_ in file_lines:
    i = i_.replace("\n", "")

    l = len(i)
    counter = 1

    exists = False
    for item in items:
        if l == item[0]:
            exists = True
            item[1] += 1
            break

    if not exists:
        items.append([l, counter])


items = sorted(items, key=itemgetter(1))


for i in items:
    print(f"{i[0]}\t{i[1]}\t({i[1]/lines_l*100:.2f}%)")
