#!/bin/bash

function utc() {
	#echo "$(date +"%Y-%m-%d %T:%N (%s)")"
	echo "$(date +"%Y-%m-%d %T")"
}

unhide_cursor() {
    printf '\e[?25h'
}
trap unhide_cursor EXIT
printf '\e[?25l'

FILES="$1"
[ -z "$FILES" ] && FILES="/home/pi/Dump/*.log"

getoutput() {
	OUTPUT_CAT="$(cat -v $FILES 2>/dev/null)"
	COUNTER_B="$(echo "$OUTPUT_CAT" | grep '\[BEACON\]' | wc -l)"
	COUNTER_HB="$(echo "$OUTPUT_CAT" | grep '\[HIDDEN BEACON\]' | wc -l)"
	COUNTER_BHB=$(($COUNTER_B + $COUNTER_HB))
	COUNTER_PR="$(echo "$OUTPUT_CAT" | grep '\[PROBERESPONSE\]' | wc -l)"
	COUNTER_RPR="$(echo "$OUTPUT_CAT" | grep '\[ROGUE PROBERESPONSE\]' | wc -l)"
	COUNTER_PRRPR=$(($COUNTER_PR + $COUNTER_RPR))
	COUNTER_AU="$(echo "$OUTPUT_CAT" | grep '\[AUTHENTICATION\]' | wc -l)"
	COUNTER_AS="$(echo "$OUTPUT_CAT" | grep '\[ASSOCIATION\]' | wc -l)"
	COUNTER_RAS="$(echo "$OUTPUT_CAT" | grep '\[REASSOCIATION\]' | wc -l)"
	COUNTER_AUASRAS=$(($COUNTER_AU + $COUNTER_AS + $COUNTER_RAS))
	COUNTER_PK="$(echo "$OUTPUT_CAT" | grep '\[PMKID:' | wc -l)"
	COUNTER_PKR="$(echo "$OUTPUT_CAT" | grep '\[PMKIDROGUE:' | wc -l)"
	COUNTER_PKPKR=$(($COUNTER_PK + $COUNTER_PKR))
	COUNTER_E="$(echo "$OUTPUT_CAT" | grep '\[EAPOL:' | wc -l)"
	COUNTER_H=$(($COUNTER_PKPKR + $COUNTER_E))
	TIMENOW=$(utc)

	echo -e "\e[95mT\e[0m.........: \e[95m$TIMENOW\e[0m"
	echo -e "\e[92mBEAC\e[0m+\e[32mHIDD\e[0m.: \e[1;92m$COUNTER_BHB\e[0m (\e[92m$COUNTER_B\e[0m+\e[32m$COUNTER_HB\e[0m)"
	echo -e "\e[93mPROB\e[0m+\e[33mROGU\e[0m.: \e[1;93m$COUNTER_PRRPR\e[0m (\e[93m$COUNTER_PR\e[0m+\e[33m$COUNTER_RPR\e[0m)"
	echo -e "\e[36mAUTH\e[0m+\e[1;36m(RE)\e[0m\e[96mA\e[0m: \e[1;96m$COUNTER_AUASRAS\e[0m (\e[36m$COUNTER_AU\e[0m+\e[1;36m$COUNTER_RAS\e[0m+\e[96m$COUNTER_AS\e[0m)"
	echo -e "\e[31mPMK\e[0m+\e[91mPMKR\e[0m+\e[1;31mE\e[0m: \e[1;91m$COUNTER_H\e[0m (\e[31m$COUNTER_PK\e[0m+\e[91m$COUNTER_PKR\e[0m+\e[1;31m$COUNTER_E\e[0m)\e[0m"
}

tput clear
HOME=$(tput cup 0 0)

while true
do
	printf '%s' "$HOME"
	getoutput
	sleep 2
done
