#!/bin/bash

function utc() {
	#echo "$(date +"%Y-%m-%d %T:%N (%s)")"
	echo "$(date +"%Y-%m-%d %T")"
}

unhide_cursor() {
    printf '\e[?25h'
}
trap unhide_cursor EXIT
printf '\e[?25l'

FILES="$1"
[ -z "$FILES" ] && FILES="/home/pi/Dump/*.log"

tput clear

while true
do
	tput cup 0 0
	/home/pi/.vip/scripts/pi_log1
	sleep 2
done
