#!/bin/bash

function utc() {
	#echo "$(date +"%Y-%m-%d %T:%N (%s)")"
	echo "$(date +"%Y-%m-%d %T")"
}

unhide_cursor() {
    printf '\e[?25h'
}
trap unhide_cursor EXIT
printf '\e[?25l'

tput clear

while true
do
	tput cup 0 0
	pi_log1
	sleep 2
done
