#!/usr/bin/env python3

import sys

if len(sys.argv) <= 1:
	print("ABOUT: remove lines with utf-8")
	print("USAGE: " + sys.argv[0] + " <file>")
	exit()

file1 = open(sys.argv[1], 'r')
lines1 = file1.readlines()
file1.close()

def checkUTF(s):
	no_special = True
	try:
		s.encode('latin1')
	except UnicodeEncodeError:
		no_special = False
	return no_special

for l1 in lines1:
	line1 = l1.replace("\n", "")
	if checkUTF(line1):
		print(line1)

