#!/usr/bin/env bash


INPUT="$1"

if [ ! -d "$INPUT" ]; then
        echo "dir not found."
        exit 1
fi

read -p "shred '$INPUT' dir? [y/n]: " yn



case $yn in 
        [yY] )
                echo "shredding: $INPUT ...";
                find "$INPUT" -type f -exec shred -n 0 -uvz {} \;
                ;;
        [nN] )
                exit 0;
                ;;
        * )
                exit 0;
                ;;
esac
