#!/usr/bin/env python3
import sys
from tabulate import tabulate
from operator import itemgetter
#from colorama import Fore, Back, Style

if len(sys.argv) < 2:
    print("USAGE: " + sys.argv[0] + " <file.csv> [delim] [-h]")
    print("* delim default = whitepace")
    print(" -h = first line is header")
    exit()

items = []

filename = sys.argv[1]
delim = ""
clm = ""
hasHeader = False
if len(sys.argv) >= 3: delim = sys.argv[2]
if len(sys.argv) >= 4 and sys.argv[3] == "-h": hasHeader = True

f = open(filename, 'r')
lines = f.readlines()
f.close()
for i_ in lines:
    i = i_.replace("\n", "")
    if delim: a = i.split(delim)
    else:     a = i.split()
    items.append(a)

heads = []
heads_len = len(items[0])

if hasHeader:
    heads = items[0]
    del items[0]
else:
    for i in range(heads_len):
        heads.append(i)

print(tabulate(items, headers=heads))

