#!/usr/bin/env python3
import sys
import time
import atexit
import getchlib

from tabulate import tabulate
from operator import itemgetter
#from colorama import Fore, Back, Style


items = []

f = open(sys.argv[1], 'r')
lines = f.readlines()
f.close()
for i_ in lines:
    i = i_.replace("\n", "")
    a = i.split()
    items.append(a)

heads = []
heads_len = len(items[0])
for i in range(heads_len):
    heads.append(i)

sortwith = 0
if len(sys.argv) >= 3:
    sortwith = int(sys.argv[2])

print(tabulate(sorted(items, key=itemgetter(sortwith)), headers=heads))

