#!/usr/bin/env python3

import subprocess
from colorama import Fore, Back, Style


delim = "  "

clr_reset = Style.RESET_ALL
clr_wlan  = Style.BRIGHT + Fore.RED
clr_bssid = Style.NORMAL + Fore.GREEN
clr_ch    = Style.BRIGHT + Fore.YELLOW
clr_fq    = Style.NORMAL + Fore.YELLOW
clr_q     = Style.NORMAL + Fore.CYAN
clr_enc   = Style.BRIGHT + Fore.BLUE
clr_essid = Style.BRIGHT + Fore.MAGENTA

header = [
    clr_bssid + "BSSID"         + clr_reset,
    clr_ch    + "CH"            + clr_reset,
    clr_fq    + "FQ"            + clr_reset,
    clr_q     + "Quality & PWR" + clr_reset,
    clr_enc   + "ENC"           + clr_reset,
    clr_essid + "ESSID"         + clr_reset
]

for i in header:
    print(i, end=" | ")

print("\n\n")

for i in subprocess.run(['sudo', 'iwlist', 'scan'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout.decode().split("\n"):
    if "Scan completed" in i:
        print("\n" + clr_wlan  + i.split()[0] + ":" + clr_reset)
        continue
    if "Address:" in i:
        print(" " + clr_bssid + i.split("Address: ", 1)[1] + clr_reset, end=delim)
        continue
    if "Channel:" in i:
        print(clr_ch + i.split("Channel:", 1)[1] + clr_reset, end=delim)
        continue
    if "Frequency:" in i:
        print(clr_fq + i.split("Frequency:", 1)[1].split(" (Channel", 1)[0] + clr_reset, end=delim)
        continue
    if "Quality=" in i:
        print(clr_q + i.split("Quality=", 1)[1].replace(" Signal level=", "")[:-2] + clr_reset, end=delim)
        continue
    if "Encryption key:" in i:
        print(clr_enc + i.split("Encryption key:", 1)[1] + clr_reset, end=delim)
        continue
    if "ESSID:" in i:
        print(clr_essid + i.split("ESSID:", 1)[1] + clr_reset)
        continue
