#!/usr/bin/env bash
set -x
git clone https://github.com/0000xFFFF/3dview
git clone https://github.com/0000xFFFF/4chan-dl
git clone https://github.com/0000xFFFF/4chan-masonry
git clone https://github.com/0000xFFFF/ai-image-desc
git clone https://github.com/0000xFFFF/apple-bssid-geoloc
git clone https://github.com/0000xFFFF/BAS-TIMER
git clone https://github.com/0000xFFFF/bat
git clone https://github.com/0000xFFFF/beatport-genre
git clone https://github.com/0000xFFFF/beep
git clone https://github.com/0000xFFFF/bg-color-palette-lab
git clone https://github.com/0000xFFFF/cnn-emnist-cam
git clone https://github.com/0000xFFFF/dahua_camera_ffplay
git clone https://github.com/0000xFFFF/dahua_camera_motion
git clone https://github.com/0000xFFFF/dotfiles
git clone https://github.com/0000xFFFF/dumpit
git clone https://github.com/0000xFFFF/dumpit-old
git clone https://github.com/0000xFFFF/dwm
git clone https://github.com/0000xFFFF/fapmap
git clone https://github.com/0000xFFFF/first-order-model
git clone https://github.com/0000xFFFF/fscan
git clone https://github.com/0000xFFFF/gridview
git clone https://github.com/0000xFFFF/gridview-flask
git clone https://github.com/0000xFFFF/hcx-fastgenlst
git clone https://github.com/0000xFFFF/hcx-scripts
git clone https://github.com/0000xFFFF/junkyard
git clone https://github.com/0000xFFFF/kaladont
git clone https://github.com/0000xFFFF/L3MON
git clone https://github.com/0000xFFFF/muslp
git clone https://github.com/0000xFFFF/PRET
git clone https://github.com/0000xFFFF/primebd
git clone https://github.com/0000xFFFF/primebd-dev
git clone https://github.com/0000xFFFF/prnt.sc_scraper
git clone https://github.com/0000xFFFF/random-exploits
git clone https://github.com/0000xFFFF/reghacks
git clone https://github.com/0000xFFFF/silentripper
git clone https://github.com/0000xFFFF/UserScripts
git clone https://github.com/0000xFFFF/utrack
git clone https://github.com/0000xFFFF/vip
git clone https://github.com/0000xFFFF/webgrab
git clone https://github.com/0000xFFFF/win-utils-cpp
git clone https://github.com/0000xFFFF/win-utils-cs
git clone https://github.com/0000xFFFF/wlst
git clone https://github.com/0000xFFFF/YTthumb
