#!/bin/bash
xrandr --output DisplayPort-0 --primary --mode 1920x1200 --pos 1920x0 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --mode 1280x1024 --pos 3840x165 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 0x109 --rotate normal
