#!/usr/bin/env python3

import sys
from threading import Thread
from scapy.all import *

# Dot11ATIM, Dot11Ack, Dot11AssoReq, Dot11AssoResp, Dot11Auth, Dot11Beacon, Dot11Deauth, Dot11Disas, Dot11ProbeReq, Dot11ProbeResp, Dot11ReassoReq, Dot11ReassoResp, LLC

interface = "wlp0s26u1u2mon"

channels = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ]
def hopch(i): os.system(f"sudo iw dev '{interface}' set channel {i}")

def thread_hopch():
    while True:
        for i in channels:
            hopch(i)
            time.sleep(1)

def callback(packet):
    if packet.haslayer(Dot11Deauth):
        print(packet.addr1, packet.addr2, packet.addr3)


if __name__ == "__main__":
    th_hop = Thread(target=thread_hopch)
    th_hop.start()

    sniff(prn=callback, iface=interface)
