#!/bin/bash

WLANDEVICE="$1"
FILENAME="$(date +"%s")_$RANDOM"

# shellcheck disable=SC2024
sudo /home/pi/.vip/scripts/pi_hcxdumptool "$WLANDEVICE" "$FILENAME" 2>&1 | tee -a "/home/pi/Dump/$FILENAME.log"

