#!/usr/bin/env python3
import RPi.GPIO as GPIO
import subprocess
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(3, GPIO.IN, pull_up_down=GPIO.PUD_UP)
GPIO.wait_for_edge(3, GPIO.FALLING)

subprocess.call(['pkill', '-INT', 'hcxdumptool'])
time.sleep(1)
subprocess.call(['shutdown', '-h', 'now'])
